### ISSUE TITLE
Can't find licensing terms

### ISSUE THREAD

**Issue by Warbo** [studio/studio#51]
Hello, this project looks really cool; I'm a heavy user of Nix, and a long time fan of Smalltalk (although not had reason to use it in anger yet!).

I'm a bit wary of downloading this to try it out though, since I can't seem to find any licensing terms for the code. Maybe they're just buried somewhere I didn't look? It's common to put terms into a file called `COPYING` or `LICENSE` at the top of the respository. Since you're using Nix, you could also use the metadata field in `default.nix`; that way, it will interact properly with Nix's `allowUnfree` option :)

**Comment by lukego** [comment]
Hi @Warbo! Great to hear that I am not the only person who likes both Nix and is open to an excuse to hack some Smalltalk in anger :-)

I added a LICENSE file specifying Apache 2.0 in #54. Hope that helps!

**Comment by Warbo** [comment]
Thanks, that clarifies things :)
