### ISSUE TITLE
UI hangs when clicking on Profiler datasets

### ISSUE THREAD

**Issue by raj2569** [studio/studio#76]
After launching studio for the first time and  loading `snabb.processDirectory` A window with `Profiler datasets` appear. When clicking a `Profile` in the window, it takes along time for UI to refresh. During this  time I am not able to scroll this window to see other items nor UI responds to any other clicks.

The shm directory I am using has a size of 106MB, which might be the reason why it takes so long. But an indication about studio being busy and a progress bar would be nice.

**Comment by raj2569** [comment]
After testing with a085849  the UI speed is much better, I guess if you can change he pointer to hour glass, we can live with this issue for now.

**Comment by lukego** [comment]
Closing now that the UI is somewhat optimized and progress messages have been added in #78.
